[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 