name: Clash Royale API Proxy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [proxy_request]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Proxy Request
        uses: actions/github-script@v6
        with:
          script: |
            const tag = context.payload.client_payload.tag;
            if (!tag) {
              return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Tag não fornecida' })
              };
            }

            const response = await fetch(`https://api.clashroyale.com/v1/players/%23${tag}`, {
              headers: {
                'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM4MDFlOGM5LWRhYjctNDdmMi1hYzA0LTgxNTdiODVhYmZiMSIsImlhdCI6MTc0ODc5ODA4MCwic3ViIjoiZGV2ZWxvcGVyLzJjMjhkZjZiLTY0N2ItN2IxNi04NjZlLWFhODVlMGU0ZjdkYiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI3OC4xMzcuMjEzLjMwIl0sInR5cGUiOiJjbGllbnQifV19.SCuXaJ1GgDzBhvDyqQrNblIp6NU3xKA2nBnc-7KnyzysVQfbJLLf1jQd3SLdTKX6IP1T7qLTHrB81D0cnjUnvA',
                'Accept': 'application/json'
              }
            });

            const data = await response.json();
            return {
              statusCode: response.status,
              body: JSON.stringify(data)
            }; 